package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/NON_EXISTENT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON3/workspace/8-2-build-linux-amd64/jdk8u121/8372/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Monday, December 12, 2016 4:37:46 PM PST
*/

public interface NON_EXISTENT
{

  /** Object adapter state indicating that the adapter has been destroyed.
     */
  public static final short value = (short)(4);
}
